[package]
name = "reggy-fs"
version = "0.1.0"
edition = "2024"

[lib]
path = "src/lib.rs"

[dependencies]
reggy-core = { path = "../reggy-core" }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
