[package]
name = "reggy-core"
version = "0.1.0"
edition = "2024"

[lib]
path = "src/lib.rs"

[dependencies]
regex = "1.11.0"
lazy_static = "1.5.0"
uuid = { workspace = true }
log = "0.4"
sha256 = "1.6.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
