[package]
name = "reggy-api"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = "0.8.4"
serde = { version = "1.0.209", features = ["derive"] }
tokio = { version = "1.40.0", features = ["full"] }
reggy-core = { path = "../reggy-core" }
reggy-fs = { path = "../reggy-fs" }
serde_json = "1.0"

